attempt fix for github action

diff --git a/.github/workflows/lint-and-test.yml b/.github/workflows/lint-and-test.yml
--- a/.github/workflows/lint-and-test.yml
+++ b/.github/workflows/lint-and-test.yml
@@ -94,6 +94,14 @@ jobs:
           java-version: ${{ matrix.java-version }}
           cache: maven
 
+      - name: Force redownload xml-apis-ext if corrupted
+        run: |
+           rm -rf ~/.m2/repository/xml-apis/xml-apis-ext/1.3.04 || true
+           mvn dependency:get \
+             -Dartifact=xml-apis:xml-apis-ext:1.3.04 \
+             -DrepoUrl=https://repo.maven.apache.org/maven2 \
+             -Dtransitive=false || true     # don't fail whole job if repo is flaky
+
       - name: Setup filestore
         run: |
           rm -rf $RS_FILE_BASE
